title: Pouran Nazarian Samani
logo: https://github.com/pouransamani/pouransamani.github.io/blob/089e037baf63f069e450e3f32388fa33be5121e9/Pouran%20photo%20Github_modi.png
description: "Data Scientist Portfolio"
show_downloads: true
theme: jekyll-theme-minimal
    
