title: "Pouran Nazarian Samani"
logo: "/assets/images/Pouran_photo.jpg?raw=true"

description: >
  Junior Data Scientist with over a decade of experience in project management and geology, 
  transitioning into data analysis & BI. Skilled in developing predictive models, data querying, 
  cleaning, and feature engineering using machine learning techniques. 
  Leveraging a strong analytical mindset shaped by geological research and project management expertise, 
  I excel at identifying patterns, solving complex problems, and delivering data-driven insights.

  Seeking opportunities to drive business growth through strategic data utilization & AI-powered solutions 
  to bring efficiency & innovation. I'd love to connect & explore how my experience can contribute to your team.

show_downloads: true
theme: jekyll-theme-minimal

# External links (add them to your index.html or footer.html instead)
github_url: "https://github.com/pouransamani"
linkedin_url: "https://www.linkedin.com/in/pouran-samani-9468643a/"
resume_url: "https://github.com/pouransamani/pouransamani.github.io/tree/884cf9c936fe5fc80df6e88fdb120976f58298ab/PDF/Pouran_CV-DS_PM.pdf"
