title: Pouran Nazarian Samani
logo: https://github.com/pouransamani/pouransamani.github.io/blob/ce7587732a18b0017051d188e844f828aa98f78f/Pouran%20photo%20Github.jpg
description: "Data Scientist Portfolio"
show_downloads: true
theme: jekyll-theme-minimal
    
